version: 2
jobs:
  build:
    docker:
      - image: golang:1.14
    environment:
      GO111MODULE: "on"
    working_directory: /ledger-go
    steps:
      - checkout
      - run: go test -tags ledger_mock
workflows:
  version: 2
  build_all:
    jobs:
      - build
